module VerifyExamples.Generic.Get0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)
import Generic.Decoder exposing (decode)







spec0 : Test.Test
spec0 =
    Test.test "#get: \n\n    \"{\\\"type\\\": [1, [2, \\\"tada\\\"] ]}\"\n        |> decode\n        |> Result.withDefault Null\n        |> get [Int 99]\n        |> Maybe.andThen toString\n        |> (==) Nothing\n    --> True" <|
        \() ->
            Expect.equal
                (
                "{\"type\": [1, [2, \"tada\"] ]}"
                    |> decode
                    |> Result.withDefault Null
                    |> get [Int 99]
                    |> Maybe.andThen toString
                    |> (==) Nothing
                )
                (
                True
                )