module VerifyExamples.Generic.ToBool7 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)







spec7 : Test.Test
spec7 =
    Test.test "#toBool: \n\n    toBool (Bool False)\n    --> False" <|
        \() ->
            Expect.equal
                (
                toBool (Bool False)
                )
                (
                False
                )