module VerifyExamples.Generic.ToBool8 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)







spec8 : Test.Test
spec8 =
    Test.test "#toBool: \n\n    toBool (Bool True)\n    --> True" <|
        \() ->
            Expect.equal
                (
                toBool (Bool True)
                )
                (
                True
                )