module VerifyExamples.Generic.ToBool9 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)







spec9 : Test.Test
spec9 =
    Test.test "#toBool: \n\n    toBool Null\n    --> False" <|
        \() ->
            Expect.equal
                (
                toBool Null
                )
                (
                False
                )