module VerifyExamples.Generic.ToBool2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)







spec2 : Test.Test
spec2 =
    Test.test "#toBool: \n\n    toBool (String \"\")\n    --> False" <|
        \() ->
            Expect.equal
                (
                toBool (String "")
                )
                (
                False
                )