module VerifyExamples.Generic.ToBool1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#toBool: \n\n    toBool (String \"misc\")\n    --> True" <|
        \() ->
            Expect.equal
                (
                toBool (String "misc")
                )
                (
                True
                )