module VerifyExamples.Generic.ToBool0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#toBool: \n\n    toBool (List [])\n    --> True" <|
        \() ->
            Expect.equal
                (
                toBool (List [])
                )
                (
                True
                )