module VerifyExamples.Generic.ToBool6 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)







spec6 : Test.Test
spec6 =
    Test.test "#toBool: \n\n    toBool (Int 0)\n    --> False" <|
        \() ->
            Expect.equal
                (
                toBool (Int 0)
                )
                (
                False
                )