module VerifyExamples.Generic.ToFloat8 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)
import Generic as Gen







spec8 : Test.Test
spec8 =
    Test.test "#toFloat: \n\n    Gen.toFloat (Bool False)\n    --> Just 0.0" <|
        \() ->
            Expect.equal
                (
                Gen.toFloat (Bool False)
                )
                (
                Just 0.0
                )