module VerifyExamples.Generic.ToFloat7 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)
import Generic as Gen







spec7 : Test.Test
spec7 =
    Test.test "#toFloat: \n\n    Gen.toFloat (Int 2)\n    --> Just 2.0" <|
        \() ->
            Expect.equal
                (
                Gen.toFloat (Int 2)
                )
                (
                Just 2.0
                )