module VerifyExamples.Generic.ToFloat6 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)
import Generic as Gen







spec6 : Test.Test
spec6 =
    Test.test "#toFloat: \n\n    Gen.toFloat (Int -1)\n    --> Just -1.0" <|
        \() ->
            Expect.equal
                (
                Gen.toFloat (Int -1)
                )
                (
                Just -1.0
                )