module VerifyExamples.Generic.ToFloat3 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)
import Generic as Gen







spec3 : Test.Test
spec3 =
    Test.test "#toFloat: \n\n    Gen.toFloat (String \"\")\n    --> Nothing" <|
        \() ->
            Expect.equal
                (
                Gen.toFloat (String "")
                )
                (
                Nothing
                )