module VerifyExamples.Generic.ToFloat0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)
import Generic as Gen







spec0 : Test.Test
spec0 =
    Test.test "#toFloat: \n\n    Gen.toFloat (String \"33.33\")\n    --> Just 33.33" <|
        \() ->
            Expect.equal
                (
                Gen.toFloat (String "33.33")
                )
                (
                Just 33.33
                )