module VerifyExamples.Generic.ToInt5 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)







spec5 : Test.Test
spec5 =
    Test.test "#toInt: \n\n    toInt (Int -1)\n    --> Just -1" <|
        \() ->
            Expect.equal
                (
                toInt (Int -1)
                )
                (
                Just -1
                )