module VerifyExamples.Generic.ToInt4 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)







spec4 : Test.Test
spec4 =
    Test.test "#toInt: \n\n    toInt (Float 0.0)\n    --> Just 0" <|
        \() ->
            Expect.equal
                (
                toInt (Float 0.0)
                )
                (
                Just 0
                )