module VerifyExamples.Generic.ToInt0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#toInt: \n\n    toInt (String \"33.33\")\n    --> Just 33" <|
        \() ->
            Expect.equal
                (
                toInt (String "33.33")
                )
                (
                Just 33
                )