module VerifyExamples.Generic.ToInt1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#toInt: \n\n    toInt (String \"33\")\n    --> Just 33" <|
        \() ->
            Expect.equal
                (
                toInt (String "33")
                )
                (
                Just 33
                )