module VerifyExamples.Generic.ToInt8 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)







spec8 : Test.Test
spec8 =
    Test.test "#toInt: \n\n    toInt (Bool True)\n    --> Just 1" <|
        \() ->
            Expect.equal
                (
                toInt (Bool True)
                )
                (
                Just 1
                )