module VerifyExamples.Generic.ToInt3 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)







spec3 : Test.Test
spec3 =
    Test.test "#toInt: \n\n    toInt (Float 3.141592)\n    --> Just 3" <|
        \() ->
            Expect.equal
                (
                toInt (Float 3.141592)
                )
                (
                Just 3
                )