module VerifyExamples.Generic.ToList0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)
import Generic as Gen







spec0 : Test.Test
spec0 =
    Test.test "#toList: \n\n    List [ Null, Int 12, Int 12]\n        |> toSet\n        |> Set\n        |> toList\n    --> [Int 12, Null]" <|
        \() ->
            Expect.equal
                (
                List [ Null, Int 12, Int 12]
                    |> toSet
                    |> Set
                    |> toList
                )
                (
                [Int 12, Null]
                )