module VerifyExamples.Generic.ToList1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)
import Generic as Gen







spec1 : Test.Test
spec1 =
    Test.test "#toList: \n\n    List [ Null, Int 12 ] |> toList\n    --> [Null, Int 12]" <|
        \() ->
            Expect.equal
                (
                List [ Null, Int 12 ] |> toList
                )
                (
                [Null, Int 12]
                )