module VerifyExamples.Generic.ToString5 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)







spec5 : Test.Test
spec5 =
    Test.test "#toString: \n\n    toString (Float 3.141592)\n    --> Just \"3.141592\"" <|
        \() ->
            Expect.equal
                (
                toString (Float 3.141592)
                )
                (
                Just "3.141592"
                )