module VerifyExamples.Generic.ToString10 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)







spec10 : Test.Test
spec10 =
    Test.test "#toString: \n\n    toString (Bool True)\n    --> Just \"true\"" <|
        \() ->
            Expect.equal
                (
                toString (Bool True)
                )
                (
                Just "true"
                )