module VerifyExamples.Generic.ToString1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#toString: \n\n    toString (String \"33.33\")\n    --> Just \"33.33\"" <|
        \() ->
            Expect.equal
                (
                toString (String "33.33")
                )
                (
                Just "33.33"
                )