module VerifyExamples.Generic.ToString8 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)







spec8 : Test.Test
spec8 =
    Test.test "#toString: \n\n    toString (Int 2)\n    --> Just \"2\"" <|
        \() ->
            Expect.equal
                (
                toString (Int 2)
                )
                (
                Just "2"
                )