module VerifyExamples.Generic.ToString0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#toString: \n\n    toString (List [ String \"33.33\", Null ])\n    --> Just \"[\\\"33.33\\\",null]\"" <|
        \() ->
            Expect.equal
                (
                toString (List [ String "33.33", Null ])
                )
                (
                Just "[\"33.33\",null]"
                )