module VerifyExamples.Generic.ToString7 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)







spec7 : Test.Test
spec7 =
    Test.test "#toString: \n\n    toString (Int -1)\n    --> Just \"-1\"" <|
        \() ->
            Expect.equal
                (
                toString (Int -1)
                )
                (
                Just "-1"
                )