module VerifyExamples.Generic.TypeOf0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#typeOf: \n\n    typeOf (String \"foo\")\n    --> \"string\"" <|
        \() ->
            Expect.equal
                (
                typeOf (String "foo")
                )
                (
                "string"
                )