module VerifyExamples.Generic.TypeOf2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)







spec2 : Test.Test
spec2 =
    Test.test "#typeOf: \n\n    typeOf (Int -99)\n    --> \"int\"" <|
        \() ->
            Expect.equal
                (
                typeOf (Int -99)
                )
                (
                "int"
                )