module VerifyExamples.Generic.TypeOf3 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic exposing (..)







spec3 : Test.Test
spec3 =
    Test.test "#typeOf: \n\n    typeOf (Bool True)\n    --> \"bool\"" <|
        \() ->
            Expect.equal
                (
                typeOf (Bool True)
                )
                (
                "bool"
                )