module VerifyExamples.Generic.Decoder.Decode0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic.Decoder exposing (..)
import Generic







spec0 : Test.Test
spec0 =
    Test.test "#decode: \n\n    \"\"\"\n    [\n        {\n            \"verzeichnis\": [\n            {\n                \"titel\": \"Wikipedia Städteverzeichnis\"\n            },\n            {\n                \"eintrag\": [\n                {\n                    \"stichwort\": \"Genf\"\n                },\n                {\n                    \"eintragstext\": \"Genf ist der Sitz von ...\"\n                }\n                ]\n            },\n            {\n                \"eintrag\": [\n                {\n                    \"stichwort\": \"Köln\"\n                },\n                {\n                    \"eintragstext\": \"Köln ist eine Stadt, die ...\"\n                }\n                ]\n            }\n            ]\n        }\n    ]\n    \"\"\"\n        |> decode\n        |> Result.withDefault Generic.Null\n        |> Generic.toString\n    --> Just \"[{\\\"verzeichnis\\\":[{\\\"titel\\\":\\\"Wikipedia Städteverzeichnis\\\"},{\\\"eintrag\\\":[{\\\"stichwort\\\":\\\"Genf\\\"},{\\\"eintragstext\\\":\\\"Genf ist der Sitz von ...\\\"}]},{\\\"eintrag\\\":[{\\\"stichwort\\\":\\\"Köln\\\"},{\\\"eintragstext\\\":\\\"Köln ist eine Stadt, die ...\\\"}]}]}]\"" <|
        \() ->
            Expect.equal
                (
                """
                [
                    {
                        "verzeichnis": [
                        {
                            "titel": "Wikipedia Städteverzeichnis"
                        },
                        {
                            "eintrag": [
                            {
                                "stichwort": "Genf"
                            },
                            {
                                "eintragstext": "Genf ist der Sitz von ..."
                            }
                            ]
                        },
                        {
                            "eintrag": [
                            {
                                "stichwort": "Köln"
                            },
                            {
                                "eintragstext": "Köln ist eine Stadt, die ..."
                            }
                            ]
                        }
                        ]
                    }
                ]
                """
                    |> decode
                    |> Result.withDefault Generic.Null
                    |> Generic.toString
                )
                (
                Just "[{\"verzeichnis\":[{\"titel\":\"Wikipedia Städteverzeichnis\"},{\"eintrag\":[{\"stichwort\":\"Genf\"},{\"eintragstext\":\"Genf ist der Sitz von ...\"}]},{\"eintrag\":[{\"stichwort\":\"Köln\"},{\"eintragstext\":\"Köln ist eine Stadt, die ...\"}]}]}]"
                )