module VerifyExamples.Generic.Decoder.Decode1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generic.Decoder exposing (..)
import Generic







spec1 : Test.Test
spec1 =
    Test.test "#decode: \n\n    \"\"\"\n    <verzeichnis>\n        <titel>Wikipedia Städteverzeichnis</titel>\n        <eintrag>\n            <stichwort>Genf</stichwort>\n            <eintragstext>Genf ist der Sitz von ...</eintragstext>\n        </eintrag>\n        <eintrag>\n            <stichwort>Köln</stichwort>\n            <eintragstext>Köln ist eine Stadt, die ...</eintragstext>\n        </eintrag>\n    </verzeichnis>\n    \"\"\"\n        |> decode\n        |> Result.withDefault Generic.Null\n        |> Generic.toString\n    --> Just \"[{\\\"verzeichnis\\\":[{\\\"titel\\\":\\\"Wikipedia Städteverzeichnis\\\"},{\\\"eintrag\\\":[{\\\"stichwort\\\":\\\"Genf\\\"},{\\\"eintragstext\\\":\\\"Genf ist der Sitz von ...\\\"}]},{\\\"eintrag\\\":[{\\\"stichwort\\\":\\\"Köln\\\"},{\\\"eintragstext\\\":\\\"Köln ist eine Stadt, die ...\\\"}]}]}]\"" <|
        \() ->
            Expect.equal
                (
                """
                <verzeichnis>
                    <titel>Wikipedia Städteverzeichnis</titel>
                    <eintrag>
                        <stichwort>Genf</stichwort>
                        <eintragstext>Genf ist der Sitz von ...</eintragstext>
                    </eintrag>
                    <eintrag>
                        <stichwort>Köln</stichwort>
                        <eintragstext>Köln ist eine Stadt, die ...</eintragstext>
                    </eintrag>
                </verzeichnis>
                """
                    |> decode
                    |> Result.withDefault Generic.Null
                    |> Generic.toString
                )
                (
                Just "[{\"verzeichnis\":[{\"titel\":\"Wikipedia Städteverzeichnis\"},{\"eintrag\":[{\"stichwort\":\"Genf\"},{\"eintragstext\":\"Genf ist der Sitz von ...\"}]},{\"eintrag\":[{\"stichwort\":\"Köln\"},{\"eintragstext\":\"Köln ist eine Stadt, die ...\"}]}]}]"
                )